BEGIN {
    print "%% This is a generated file"
    print "%% Do not edit this file manually"
    print "%%"
    print "%% To update this file, edit DICTIONARY.txt and rerun"
    print "%% GENERATE-DICTIONARY.sh"
    print ""
}

# Skip comments.
/^#/ { next }

# Lines that contain only a single field and a '>' token are references.
NF < 2 && $1 ~ ">" {
    # Split by '>' token.
    split($0, refs, ">")

    # Print reference.
    print "\\refentry{" refs[1] "}{" refs[2] "}"
    next
}

# Ignore empty lines.
NF < 2 { next }

# Format entries.
{
    # If the third field contains no spaces, assume it is a PF word.
    third = $3
    if ($3 !~ / / && length($3) > 0) third = "\\pfabbr " third

    # Main fields.
    printf "%s", "\\entry" "{" $1 "}{" $2 "}{" third "}{" $4 "}{" $5 "}"

    # Final newline.
    printf "\n"
}